version: '2.1'

services:
  frontend:
    build: frontend/.
    ports:
      - "4444:80"
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend

  backend:
    build: backend/.
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/persons" ]
      interval: 30s
      timeout: 10s
      retries: 5
